
export default {
  LOAD_PROVERBS_SUCCESS     : 'LOAD_PROVERBS_SUCCESS',
  LOAD_PROVERB_SUCCESS      : 'LOAD_PROVERB_SUCCESS',
  UPDATE_PROVERB_SUCCESS    : 'UPDATE_PROVERB_SUCCESS',
  CREATE_PROVERB_SUCCESS    : 'CREATE_PROVERB_SUCCESS',
  LOAD_TRANSLATIONS_SUCCESS : 'LOAD_TRANSLATIONS_SUCCESS',
  LOAD_TRANSLATION_SUCCESS  : 'LOAD_TRANSLATION_SUCCESS',
  UPDATE_TRANSLATION_SUCCESS: 'UPDATE_TRANSLATION_SUCCESS',
  SAVE_PROVERB_ERROR        : 'SAVE_PROVERB_ERROR'
};
